const { users, getUserName } = require('./exercise2e3');

describe('Faz os testes solicitados na quest達o 2', () => {
  it('Caso ID seja encontrado', () => {
    expect.assertions(1);
    return getUserName(4)
    .then((data) => {
      expect(data).toBeTruthy();
    });
  });
  it('Caso ID N達o seja encontrado', () => {
    expect.assertions(1);
    getUserName(6)
    .catch((error) => {
      expect(error).toEqual({"error": "User with 6 not found."});
    });
  });
});

describe('Faz os testes solicitados na quest達o 2 porem com async', () => {
  it('Caso ID seja encontrado', async () => {
    expect.assertions(1);
    const data = await getUserName(4);
    expect(data).toBeTruthy();
  });
  it('Caso ID N達o seja encontrado', async () => {
    expect.assertions(1);
    try {
      await getUserName(6);
    }
    catch(error) {
      expect(error).toEqual({"error": "User with 6 not found."});
    }
  });
});
